"""The Loom's generator — weave a platform's bilingual surface from its manifest.

One manifest + one weave config in, three artifacts out (ADR-060 §1, §4):

  mcp-packet/     the npm MCP server (3-file windy-word-mcp skeleton) —
                  the language outside agents speak
  python_twin.py  windy-agent Capability registrations — the language
                  Windy Fly speaks
  conformance_driver.py  the parity gate a platform wires into make check

Both adapters proxy the SAME native transport (`POST /invoke` on the
platform's control server, ADR-060 §3.2), so there is exactly one
implementation of every knob. The packet embeds a byte-identical copy of
the manifest; the conformance driver fails if embedded and source ever
differ — drift is a test failure, not a code review hope.

Output is DETERMINISTIC: same inputs → byte-identical outputs (no
timestamps), so "regenerate and diff" is itself a drift gate.

Usage:
    uv run python -m loom.generate <manifest.json> <weave.json> <outdir>
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import jsonschema

from loom.validate import validate_manifest

_SCHEMA_DIR = Path(__file__).resolve().parent.parent / "schema"

_GENERATED_BANNER = "GENERATED by the Loom (windy-contracts) — DO NOT EDIT. Edit the manifest and re-weave."


def _load_weave_schema() -> dict:
    return json.loads((_SCHEMA_DIR / "weave-config.v1.schema.json").read_text())


def validate_weave(weave: dict) -> list[str]:
    v = jsonschema.Draft202012Validator(_load_weave_schema())
    return [
        f"{'/'.join(str(p) for p in e.absolute_path) or '<root>'}: {e.message}"
        for e in sorted(v.iter_errors(weave), key=lambda e: list(e.absolute_path))
    ]


# ── emitter 1: the MCP packet ────────────────────────────────────────


def emit_mcp_packet(manifest: dict, weave: dict) -> dict[str, str]:
    """Return {relative_path: content} for the npm packet."""
    pkg = weave["package"]
    product = weave["product"]
    bin_name = pkg["name"]

    package_json = json.dumps(
        {
            "name": pkg["name"],
            "version": pkg["version"],
            "description": pkg.get(
                "description",
                f"MCP server for {product} — thin wrapper over its native control surface.",
            ),
            "type": "module",
            "bin": {bin_name: "bin/cli.js"},
            "files": ["bin", "src", "manifest.json"],
            "dependencies": {"@modelcontextprotocol/sdk": "^1.0.0"},
            "loom": {"contract": manifest["contract"], "generated": True},
        },
        indent=2,
    ) + "\n"

    manifest_json = json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"

    auth = weave["auth"]
    if auth["kind"] == "install_token":
        auth_js = f"""// Per-install token (ADR-060 §3.3, Class D wall). Read fresh per request
// so a token minted or rotated after this server starts needs no restart.
import {{ readFileSync }} from 'node:fs';
import {{ homedir }} from 'node:os';

const TOKEN_PATH = process.env.{auth.get('token_path_env', 'WINDY_CONTROL_TOKEN_PATH')}
  || {json.dumps(auth.get('token_path_default', ''))}.replace('~', homedir());

export function authHeaders() {{
  const envTok = process.env.{auth.get('token_env', 'WINDY_CONTROL_TOKEN')};
  if (envTok) return {{ authorization: `Bearer ${{envTok}}` }};
  try {{
    const t = readFileSync(TOKEN_PATH, 'utf8').trim();
    return t ? {{ authorization: `Bearer ${{t}}` }} : {{}};
  }} catch {{
    return {{}}; // pre-token build, or app not yet run — surface will 401 with remediation
  }}
}}
"""
    else:  # ept
        auth_js = f"""// EPT auth (ADR-060 §3.3, Class C wall). The passport rides as a bearer;
// the surface maps it to an EI band and filters discovery accordingly.
export function authHeaders() {{
  const ept = process.env.{auth.get('token_env', 'WINDY_EPT')};
  return ept ? {{ authorization: `Bearer ${{ept}}` }} : {{}};
}}
"""

    base_env = weave["http"].get("base_env", "WINDY_CONTROL_URL")
    client_js = f"""// {_GENERATED_BANNER}
// Native-transport client for {product}. Each tool reaches the SAME live
// implementation the human UI uses (ADR-060 §1). Greenfield tools proxy
// POST /invoke {{name, arguments}}; Gen-1 tools that declare a `transport`
// binding call their bespoke REST route, so an already-hardened surface
// (e.g. Windy Word :18765) is never rewritten. The route table is derived
// from the embedded manifest, so it cannot drift from tools/list.
{auth_js}
const BASE = (process.env.{base_env} || {json.dumps(weave['http']['base_default'])}).replace(/\\/$/, '');

// name -> {{ method, path, arg_mapping }} for tools with an explicit binding.
export function buildRouteTable(manifest) {{
  const table = {{}};
  for (const t of manifest.tools) {{
    if (t.transport) {{
      const m = t.transport.method;
      table[t.name] = {{
        method: m,
        path: t.transport.path,
        argMapping: t.transport.arg_mapping || (m === 'GET' ? 'query' : 'body'),
      }};
    }}
  }}
  return table;
}}

async function fetchJson(url, init, timeoutMs) {{
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  init.signal = controller.signal;
  let res;
  try {{
    res = await fetch(url, init);
  }} catch (err) {{
    clearTimeout(timer);
    if (err.name === 'AbortError') return {{ ok: false, error: `{product} control surface timed out after ${{timeoutMs}}ms.` }};
    return {{ ok: false, error: `{product} control surface unreachable at ${{BASE}} — is it running? (${{err.cause?.code || err.message}})` }};
  }}
  clearTimeout(timer);
  const text = await res.text();
  let parsed;
  try {{ parsed = JSON.parse(text); }}
  catch {{ return res.ok ? {{ ok: true, raw: text }} : {{ ok: false, error: text || `HTTP ${{res.status}}` }}; }}
  // A bespoke route that returns 4xx/5xx JSON without an ok flag: normalize
  // so the agent always sees {{ok:false}} (the 401 remediation body survives).
  if (!res.ok && (parsed == null || parsed.ok === undefined)) return {{ ok: false, ...(parsed || {{}}) }};
  return parsed;
}}

// extraHeaders (e.g. a remote caller's own EPT, passed through by the
// streamable-http host) WINS over this process's ambient credentials —
// identity flows through the shim; the platform's wall stays authoritative.
export async function invoke(name, args, timeoutMs = 15000, routeTable = null, extraHeaders = null) {{
  const route = routeTable && routeTable[name];
  const headers = {{ 'content-type': 'application/json', ...authHeaders(), ...(extraHeaders || {{}}) }};
  if (route) {{
    if (route.method === 'GET') {{
      const qs = route.argMapping === 'query' && args && Object.keys(args).length
        ? '?' + new URLSearchParams(Object.entries(args).map(([k, v]) => [k, String(v)])).toString()
        : '';
      return fetchJson(`${{BASE}}${{route.path}}${{qs}}`, {{ method: 'GET', headers }}, timeoutMs);
    }}
    const body = route.argMapping === 'none' ? undefined : JSON.stringify(args ?? {{}});
    return fetchJson(`${{BASE}}${{route.path}}`, {{ method: 'POST', headers, body }}, timeoutMs);
  }}
  // greenfield default: the uniform dispatcher
  return fetchJson(`${{BASE}}/invoke`, {{
    method: 'POST', headers, body: JSON.stringify({{ name, arguments: args ?? {{}} }}),
  }}, timeoutMs);
}}

export function listToolsFromManifest(manifest) {{
  return manifest.tools.map((t) => ({{
    name: t.name,
    description: t.description,
    inputSchema: t.inputSchema,
  }}));
}}
"""

    server_js = f"""// {_GENERATED_BANNER}
// Shared MCP server builder for {product} ({manifest['contract']}):
// tools/list serves the embedded manifest VERBATIM (schema parity with the
// native transport is structural, not re-implemented), tools/call proxies
// the native routes. isError mirrors the surface's {{ok:false}} envelope.
// authOverride: per-request credentials from a remote caller (the
// streamable-http host passes the caller's EPT through); null → this
// process's own ambient credentials.
import {{ Server }} from '@modelcontextprotocol/sdk/server/index.js';
import {{ CallToolRequestSchema, ListToolsRequestSchema }} from '@modelcontextprotocol/sdk/types.js';
import {{ readFileSync }} from 'node:fs';
import {{ fileURLToPath }} from 'node:url';
import {{ dirname, join }} from 'node:path';

import {{ invoke, listToolsFromManifest, buildRouteTable }} from './client.js';

const HERE = dirname(fileURLToPath(import.meta.url));
export const manifest = JSON.parse(readFileSync(join(HERE, '..', 'manifest.json'), 'utf8'));
const routeTable = buildRouteTable(manifest); // bespoke Gen-1 route bindings, if any

export function buildServer(authOverride = null) {{
  const server = new Server(
    {{ name: {json.dumps(pkg['name'])}, version: {json.dumps(pkg['version'])} }},
    {{ capabilities: {{ tools: {{}} }} }},
  );

  server.setRequestHandler(ListToolsRequestSchema, async () => ({{
    tools: listToolsFromManifest(manifest),
  }}));

  server.setRequestHandler(CallToolRequestSchema, async (req) => {{
    const {{ name, arguments: args }} = req.params;
    if (!manifest.tools.some((t) => t.name === name)) {{
      return {{ isError: true, content: [{{ type: 'text', text: `unknown tool: ${{name}}` }}] }};
    }}
    const result = await invoke(name, args, 15000, routeTable, authOverride);
    const text = JSON.stringify(result, null, 2);
    return result && result.ok === false
      ? {{ isError: true, content: [{{ type: 'text', text }}] }}
      : {{ content: [{{ type: 'text', text }}] }};
  }});

  return server;
}}
"""

    index_js = f"""// {_GENERATED_BANNER}
// stdio entrypoint — how a LOCAL agent (Claude Code, Claude Desktop, a
// co-tenant Fly) attaches. Uses this process's ambient credentials.
import {{ StdioServerTransport }} from '@modelcontextprotocol/sdk/server/stdio.js';
import {{ buildServer, manifest }} from './server.js';

async function main() {{
  await buildServer().connect(new StdioServerTransport());
  console.error(`[{pkg['name']} {pkg['version']}] stdio ready — {manifest['contract']}, ${{manifest.tools.length}} tools`);
}}

main().catch((e) => {{ console.error('[{pkg['name']}] fatal:', e); process.exit(1); }});
"""

    cli_js = f"""#!/usr/bin/env node
// {_GENERATED_BANNER}
import '../src/index.js';
"""

    files = {
        "package.json": package_json,
        "manifest.json": manifest_json,
        "src/client.js": client_js,
        "src/server.js": server_js,
        "src/index.js": index_js,
        "bin/cli.js": cli_js,
    }

    if weave["class"] == "cloud":
        files["src/http.js"] = f"""// {_GENERATED_BANNER}
// Remote entrypoint (ADR-060 §2 Class C): Streamable HTTP MCP at /mcp so a
// HOSTED agent can reach this surface over the internet. STATELESS: one
// server+transport pair per request. AUTH PASSTHROUGH: the caller's own
// Authorization header (their EPT) is forwarded verbatim on every backend
// call — this shim holds no ambient credentials for remote callers; the
// platform's EPT wall stays the single authority. Deploy behind the
// platform's TLS proxy; binds loopback by default.
import {{ createServer }} from 'node:http';
import {{ StreamableHTTPServerTransport }} from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import {{ buildServer, manifest }} from './server.js';

const PORT = parseInt(process.env.MCP_HTTP_PORT || '8917', 10);
const HOST = process.env.MCP_HTTP_HOST || '127.0.0.1';

const httpServer = createServer((req, res) => {{
  if (req.url !== '/mcp' && !req.url.startsWith('/mcp?')) {{
    res.writeHead(404, {{ 'content-type': 'application/json' }});
    res.end(JSON.stringify({{ ok: false, error: 'MCP lives at POST /mcp' }}));
    return;
  }}
  let body = '';
  req.on('data', (c) => {{ body += c; }});
  req.on('end', async () => {{
    let parsed;
    try {{ parsed = body ? JSON.parse(body) : undefined; }}
    catch {{ res.writeHead(400); res.end(); return; }}
    const auth = req.headers['authorization'];
    const authOverride = auth ? {{ authorization: auth }} : null;
    const server = buildServer(authOverride);
    const transport = new StreamableHTTPServerTransport({{
      sessionIdGenerator: undefined, // stateless — no session pinning
      enableJsonResponse: true,
    }});
    res.on('close', () => {{ transport.close(); server.close(); }});
    try {{
      await server.connect(transport);
      await transport.handleRequest(req, res, parsed);
    }} catch (e) {{
      if (!res.headersSent) {{
        res.writeHead(500, {{ 'content-type': 'application/json' }});
        res.end(JSON.stringify({{ ok: false, error: String(e) }}));
      }}
    }}
  }});
}});

httpServer.listen(PORT, HOST, () => {{
  const bound = httpServer.address().port; // real port (PORT may be 0 = OS-assigned)
  console.error(`[{pkg['name']} {pkg['version']}] streamable-http ready at http://${{HOST}}:${{bound}}/mcp — {manifest['contract']}, ${{manifest.tools.length}} tools, auth=passthrough`);
}});
"""

    return files


# ── emitter 2: the Python twin ───────────────────────────────────────


def emit_python_twin(manifest: dict, weave: dict) -> str:
    """A windy-agent Capability module proxying the same native transport."""
    product = weave["product"]
    module = weave.get("python_module", product.replace("-", "_"))
    base_env = weave["http"].get("base_env", "WINDY_CONTROL_URL")
    auth = weave["auth"]

    mapping = json.loads((_SCHEMA_DIR / "band-ei-mapping.v1.json").read_text())
    floor_defaults = {
        k: v for k, v in mapping["band_floor_defaults"].items() if not k.startswith("$")
    }

    entries = []
    routes = {}
    for t in manifest["tools"]:
        band = t.get("band_floor", floor_defaults[t["tier"]])
        desc = json.dumps(t["description"], ensure_ascii=False)
        entries.append(
            f"    _cap(registry, {json.dumps(t['name'])}, {desc}, "
            f"{json.dumps(t['inputSchema'], ensure_ascii=False)}, "
            f"band={json.dumps(band)}, tier={json.dumps(t['tier'])})"
        )
        tr = t.get("transport")
        if tr:
            routes[t["name"]] = {
                "method": tr["method"],
                "path": tr["path"],
                "arg_mapping": tr.get("arg_mapping", "query" if tr["method"] == "GET" else "body"),
            }
    entries_src = "\n".join(entries)
    routes_src = json.dumps(routes, ensure_ascii=False, indent=4)

    if auth["kind"] == "install_token":
        token_src = f'''def _headers() -> dict[str, str]:
    token = os.environ.get({json.dumps(auth.get("token_env", "WINDY_CONTROL_TOKEN"))})
    if not token:
        path = os.environ.get(
            {json.dumps(auth.get("token_path_env", "WINDY_CONTROL_TOKEN_PATH"))},
            os.path.expanduser({json.dumps(auth.get("token_path_default", ""))}),
        )
        try:
            with open(path, encoding="utf-8") as f:
                token = f.read().strip()
        except OSError:
            token = None
    return {{"Authorization": f"Bearer {{token}}"}} if token else {{}}'''
    else:
        token_src = f'''def _headers() -> dict[str, str]:
    ept = os.environ.get({json.dumps(auth.get("token_env", "WINDY_EPT"))})
    return {{"Authorization": f"Bearer {{ept}}"}} if ept else {{}}'''

    return f'''"""{_GENERATED_BANNER}

{product} control capabilities for Windy Fly ({manifest["contract"]}).
Every capability reaches the SAME live implementation the MCP packet wraps
(ADR-060 §1: one registry, two adapters). Greenfield tools POST /invoke;
Gen-1 tools with a transport binding call their bespoke REST route (see
_ROUTES) so the hardened surface is never rewritten. Band floors come from
the manifest (or the mapping-table defaults); enforcement stays in the
Capability Plane, filtering starts at discovery.
"""

from __future__ import annotations

import os
from typing import Any

from windyfly.agent.capabilities.descriptor import Band, Capability
from windyfly.agent.capabilities.registry import CapabilityRegistry

CONTRACT = {json.dumps(manifest["contract"])}
TOOL_COUNT = {len(manifest["tools"])}

# Bespoke Gen-1 route bindings (empty for greenfield /invoke surfaces).
_ROUTES: dict[str, dict[str, str]] = {routes_src}


def _base_url() -> str:
    return os.environ.get({json.dumps(base_env)}, {json.dumps(weave["http"]["base_default"])}).rstrip("/")


{token_src}


def _normalize(r) -> dict[str, Any]:
    try:
        body = r.json()
    except Exception:
        return {{"ok": r.status_code < 400, "raw": r.text[:400]}}
    if r.status_code >= 400 and (not isinstance(body, dict) or body.get("ok") is not False):
        body = {{"ok": False, **(body if isinstance(body, dict) else {{"raw": body}})}}
    return body


def _invoke(name: str, arguments: dict[str, Any] | None = None) -> dict[str, Any]:
    import httpx

    args = arguments or {{}}
    route = _ROUTES.get(name)
    try:
        with httpx.Client(timeout=15.0) as client:
            if route is None:
                r = client.post(
                    f"{{_base_url()}}/invoke",
                    json={{"name": name, "arguments": args}},
                    headers=_headers(),
                )
            elif route["method"] == "GET":
                params = args if route["arg_mapping"] == "query" else None
                r = client.get(f"{{_base_url()}}{{route['path']}}", params=params, headers=_headers())
            else:
                json_body = None if route["arg_mapping"] == "none" else args
                r = client.post(f"{{_base_url()}}{{route['path']}}", json=json_body, headers=_headers())
        return _normalize(r)
    except httpx.ConnectError:
        return {{
            "ok": False,
            "error": "{product} control surface unreachable — is it running?",
        }}
    except Exception as e:  # never crash the turn over app control
        return {{"ok": False, "error": f"{product} control failed: {{e}}"}}


def _cap(registry: CapabilityRegistry, name: str, description: str,
         input_schema: dict[str, Any], *, band: str, tier: str) -> None:
    def handler(**kwargs: Any) -> dict[str, Any]:
        return _invoke(name, kwargs)

    registry.register(Capability(
        id=f"{module}.{{name}}",
        name=f"{product}: {{name}}",
        description=description,
        handler=handler,
        input_schema=input_schema,
        band_required=Band[band],
        audit_required=(tier != "auto_allow"),
    ))


def register_{module}_capabilities(
    registry: CapabilityRegistry,
    config: dict[str, Any] | None = None,
) -> None:
    """Register {module}.* capabilities (one per manifest tool)."""
    if os.environ.get({json.dumps("WINDY_" + module.upper() + "_CONTROL")}, "1") == "0":
        return
{entries_src}
'''


# ── emitter 3: the conformance driver ────────────────────────────────


def emit_conformance_driver(manifest: dict, weave: dict) -> str:
    product = weave["product"]
    http = weave.get("http") or {}
    base_env = http.get("base_env", "WINDY_CONTROL_URL")
    base_default = http.get("base_default", "")
    native = weave.get("server") == "native"
    return f'''"""{_GENERATED_BANNER}

Conformance driver for {product} ({manifest["contract"]}) — ADR-060 §3.7.
Wire into the platform repo's make check. Two gates:

  1. STATIC (always runs): the packet's embedded manifest.json is
     byte-identical to the source manifest — the two languages cannot
     drift because they are the same bytes.
  2. LIVE (runs when the surface is up, or FORCE_LIVE=1): GET /tools on
     the native transport returns exactly the manifest's tools — floor
     count, names, and inputSchema equality.

Exit 0 = conformant. Any drift = nonzero, with a diff you can act on.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.request
from pathlib import Path

CONTRACT = {json.dumps(manifest["contract"])}
EXPECTED_TOOL_FLOOR = {len(manifest["tools"])}


def _fail(msg: str) -> None:
    print(f"CONFORMANCE FAIL [{product}]: {{msg}}")
    sys.exit(1)


def static_gate(source_manifest: Path, packet_manifest: Path) -> None:
    src = source_manifest.read_bytes()
    pkt = packet_manifest.read_bytes()
    if src != pkt:
        _fail(f"packet manifest {{packet_manifest}} differs from source {{source_manifest}} — re-weave (loom.generate), never hand-edit")
    tools = json.loads(src)["tools"]
    if len(tools) < EXPECTED_TOOL_FLOOR:
        _fail(f"tool floor broken: {{len(tools)}} < {{EXPECTED_TOOL_FLOOR}}")
    print(f"conformance static OK: {{len(tools)}} tools, packet manifest byte-identical")


NATIVE = {native!r}


def live_gate() -> None:
    if NATIVE:
        # Class A: no HTTP surface. The registry<->MCP parity gate lives in
        # the platform repo's own tests (it needs the in-process registry) —
        # e.g. windy-agent tests/test_mcp_control_bridge.py.
        print("conformance live SKIPPED (native server — parity checked by the platform's own registry tests)")
        return
    base = os.environ.get({json.dumps(base_env)}, {json.dumps(base_default)}).rstrip("/")
    manifest = json.loads((Path(__file__).parent / "manifest.json").read_text())
    try:
        with urllib.request.urlopen(f"{{base}}/tools", timeout=5) as r:
            served = json.loads(r.read())
    except Exception as e:
        if os.environ.get("FORCE_LIVE") == "1":
            _fail(f"surface unreachable at {{base}}: {{e}}")
        print(f"conformance live SKIPPED (surface not reachable at {{base}})")
        return
    served_tools = {{t["name"]: t for t in served.get("tools", served if isinstance(served, list) else [])}}
    want = {{t["name"]: t for t in manifest["tools"]}}
    missing = sorted(set(want) - set(served_tools))
    extra = sorted(set(served_tools) - set(want))
    if missing:
        _fail(f"native transport missing tools: {{missing}}")
    if extra:
        print(f"conformance live NOTE: surface serves extra tools not in manifest: {{extra}}")
    for name, t in want.items():
        if served_tools[name].get("inputSchema") != t["inputSchema"]:
            _fail(f"inputSchema drift on '{{name}}' between manifest and native transport")
    print(f"conformance live OK: {{len(want)}} tools served with matching schemas")


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    static_gate(here / "source-manifest.json", here / "manifest.json")
    live_gate()
'''


# ── the weave ────────────────────────────────────────────────────────


def weave(manifest_path: Path, weave_path: Path, outdir: Path) -> list[str]:
    """Generate all artifacts. Returns the list of files written."""
    manifest = json.loads(manifest_path.read_text())
    weave_cfg = json.loads(weave_path.read_text())

    report = validate_manifest(manifest, path=str(manifest_path))
    if not report.ok:
        raise ValueError(f"manifest invalid, refusing to weave: {report.errors}")
    weave_errors = validate_weave(weave_cfg)
    if weave_errors:
        raise ValueError(f"weave config invalid: {weave_errors}")

    written: list[str] = []
    native = weave_cfg.get("server") == "native"

    # Class A (native server): the platform implements its own MCP server over
    # an in-process registry — a woven JS proxy would HTTP-hop to itself. The
    # Loom validates the manifest and emits only the conformance driver; the
    # server + twin are hand-written native code in the platform repo.
    if not native:
        packet = emit_mcp_packet(manifest, weave_cfg)
        for rel, content in packet.items():
            p = outdir / "mcp-packet" / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content)
            written.append(str(p.relative_to(outdir)))

        module = weave_cfg.get("python_module", weave_cfg["product"].replace("-", "_"))
        twin = outdir / f"{module}_twin.py"
        twin.write_text(emit_python_twin(manifest, weave_cfg))
        written.append(twin.name)

    outdir.mkdir(parents=True, exist_ok=True)
    driver = outdir / "conformance_driver.py"
    driver.write_text(emit_conformance_driver(manifest, weave_cfg))
    written.append(driver.name)

    # The driver's static gate needs the source manifest beside it.
    src_copy = outdir / "source-manifest.json"
    src_copy.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")
    written.append(src_copy.name)
    driver_manifest = outdir / "manifest.json"
    driver_manifest.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")
    written.append(driver_manifest.name)

    return written


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if len(args) != 3:
        print(__doc__)
        return 2
    files = weave(Path(args[0]), Path(args[1]), Path(args[2]))
    print(f"wove {len(files)} files into {args[2]}:")
    for f in files:
        print(f"  {f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
